module.exports = {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
  // someSidebar: {
  //   Docusaurus: [
  //     'docusaurus/intro',
  //     'docusaurus/style-guide',
  //     'docusaurus/mdx',
  //   ],
  //   Features: ['features/算术运算'],
  //   前端精读: {
  //     前沿技术: [],
  //   },
  // },
};
